import SideNav from "@/components/SideNav";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ChatGpt Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex items-start h-screen w-screen text-white`}
      >
        {/* Side menu */}
        <SideNav />
        {/* Chat */}
        <div className="h-full w-full bg-[#343541]">{children}</div>
      </body>
    </html>
  );
}
